<?php
/**
 * Centralized dummy data for development (no database yet)
 * NOTE: All currency values are in Sri Lankan Rupees (Rs)
 */

return [
    // Fixed waste categories (5)
    'waste_categories' => [
        'Plastic',
        'Paper',
        'Glass',
        'Metal',
        'Cardboard'
    ],

    // Users
    'customers' => [
        [
            'id' => 'C001',
            'name' => 'Alice Johnson',
            'email' => 'alice@email.com',
            'phone' => '+1234567890',
            'address' => '123 Green St, Eco City',
            'status' => 'active',
            'totalPickups' => 15,
            'totalEarnings' => 12550.00,
        ],
        [
            'id' => 'C002',
            'name' => 'Bob Smith',
            'email' => 'bob@email.com',
            'phone' => '+1234567891',
            'address' => '456 Recycle Ave, Green Town',
            'status' => 'active',
            'totalPickups' => 8,
            'totalEarnings' => 6725.00,
        ],
        [
            'id' => 'C003',
            'name' => 'Carol Davis',
            'email' => 'carol@email.com',
            'phone' => '+1234567892',
            'address' => '789 Eco Blvd, Sustainable City',
            'status' => 'suspended',
            'totalPickups' => 22,
            'totalEarnings' => 18075.00,
        ],
        [
            'id' => 'C004',
            'name' => 'David Wilson',
            'email' => 'david@email.com',
            'phone' => '+1234567893',
            'address' => '321 Green Ave, Eco Valley',
            'status' => 'pending',
            'totalPickups' => 0,
            'totalEarnings' => 0.00,
        ],
    ],

    'companies' => [
        [
            'id' => 'CO001',
            'name' => 'GreenTech Co.',
            'email' => 'contact@greentech.com',
            'phone' => '+1234567892',
            'status' => 'active',
            'totalBids' => 45,
            'totalPurchases' => 32,
        ],
        [
            'id' => 'CO002',
            'name' => 'EcoRecycle Ltd.',
            'email' => 'info@ecorecycle.com',
            'phone' => '+1234567893',
            'status' => 'pending',
            'totalBids' => 12,
            'totalPurchases' => 0,
        ],
        [
            'id' => 'CO003',
            'name' => 'WasteWorks Inc.',
            'email' => 'admin@wasteworks.com',
            'phone' => '+1234567894',
            'status' => 'active',
            'totalBids' => 28,
            'totalPurchases' => 19,
        ],
        [
            'id' => 'CO004',
            'name' => 'RecyclePro Solutions',
            'email' => 'hello@recyclepro.com',
            'phone' => '+1234567895',
            'status' => 'suspended',
            'totalBids' => 15,
            'totalPurchases' => 8,
        ],
    ],

    'collectors' => [
        [
            'id' => 'COL001',
            'name' => 'Mike Wilson',
            'email' => 'mike@company.com',
            'phone' => '+1234567894',
            'vehicleId' => 'VH001',
            'status' => 'active',
            'todayPickups' => 6,
        ],
        [
            'id' => 'COL002',
            'name' => 'Sarah Brown',
            'email' => 'sarah@company.com',
            'phone' => '+1234567895',
            'vehicleId' => 'VH002',
            'status' => 'offline',
            'todayPickups' => 0,
        ],
        [
            'id' => 'COL003',
            'name' => 'Tom Garcia',
            'email' => 'tom@company.com',
            'phone' => '+1234567896',
            'vehicleId' => 'VH003',
            'status' => 'active',
            'todayPickups' => 4,
        ],
        [
            'id' => 'COL004',
            'name' => 'Lisa Martinez',
            'email' => 'lisa@company.com',
            'phone' => '+1234567897',
            'vehicleId' => 'VH004',
            'status' => 'pending',
            'todayPickups' => 0,
        ],
    ],

    // Vehicles
    'vehicles' => [
        [
            'id' => 'VH001',
            'plateNumber' => 'ABC-1234',
            'type' => 'Pickup Truck',
            'capacity' => 2000,
            'status' => 'available',
            'lastMaintenance' => '2025-08-01',
            'nextMaintenance' => '2025-11-01',
        ],
        [
            'id' => 'VH002',
            'plateNumber' => 'XYZ-5678',
            'type' => 'Van',
            'capacity' => 1500,
            'status' => 'in-use',
            'lastMaintenance' => '2025-07-15',
            'nextMaintenance' => '2025-10-15',
        ],
        [
            'id' => 'VH003',
            'plateNumber' => 'DEF-9012',
            'type' => 'Pickup Truck',
            'capacity' => 2000,
            'status' => 'maintenance',
            'lastMaintenance' => '2025-08-10',
            'nextMaintenance' => '2025-11-10',
        ],
        [
            'id' => 'VH004',
            'plateNumber' => 'GHI-3456',
            'type' => 'Small Truck',
            'capacity' => 3000,
            'status' => 'available',
            'lastMaintenance' => '2025-06-20',
            'nextMaintenance' => '2025-09-20',
        ],
        [
            'id' => 'VH005',
            'plateNumber' => 'JKL-7890',
            'type' => 'Van',
            'capacity' => 1200,
            'status' => 'in-use',
            'lastMaintenance' => '2025-08-05',
            'nextMaintenance' => '2025-11-05',
        ],
    ],

    // Payments (amounts in Rs)
    'payments' => [
        ['id' => 'PAY001', 'type' => 'payout', 'amount' => 12550.00, 'recipient' => 'Alice Johnson', 'status' => 'completed', 'date' => '2025-08-28'],
        ['id' => 'PAY002', 'type' => 'payment', 'amount' => 45000.00, 'recipient' => 'GreenTech Co.', 'status' => 'pending', 'date' => '2025-08-28'],
        ['id' => 'PAY003', 'type' => 'payout', 'amount' => 6725.00, 'recipient' => 'Bob Smith', 'status' => 'completed', 'date' => '2025-08-27'],
        ['id' => 'PAY004', 'type' => 'payment', 'amount' => 32000.00, 'recipient' => 'EcoWaste Solutions', 'status' => 'completed', 'date' => '2025-08-27'],
        ['id' => 'PAY005', 'type' => 'payment', 'amount' => 27575.00, 'recipient' => 'RecycleCorp Ltd.', 'status' => 'completed', 'date' => '2025-08-26'],
        ['id' => 'PAY006', 'type' => 'payout', 'amount' => 8930.00, 'recipient' => 'Charlie Davis', 'status' => 'pending', 'date' => '2025-08-26'],
    ],

    // Bidding rounds (amounts/bids in Rs)
    'bidding_rounds' => [
        [
            'id' => 'BR001',
            'lotId' => 'LOT001',
            'wasteCategory' => 'Plastic',
            'quantity' => 500,
            'unit' => 'kg',
            'currentHighestBid' => 250000.00,
            'biddingCompany' => 'GreenTech Co.',
            'status' => 'active',
            'endTime' => date('Y-m-d H:i:s', strtotime('+2 hours')),
        ],
        [
            'id' => 'BR002',
            'lotId' => 'LOT002',
            'wasteCategory' => 'Cardboard',
            'quantity' => 1200,
            'unit' => 'kg',
            'currentHighestBid' => 180000.00,
            'biddingCompany' => 'EcoRecycle Ltd.',
            'status' => 'active',
            'endTime' => date('Y-m-d H:i:s', strtotime('+4 hours')),
        ],
        [
            'id' => 'BR003',
            'lotId' => 'LOT003',
            'wasteCategory' => 'Metal',
            'quantity' => 300,
            'unit' => 'kg',
            'currentHighestBid' => 450000.00,
            'biddingCompany' => 'MetalWorks Inc.',
            'status' => 'completed',
            'endTime' => date('Y-m-d H:i:s', strtotime('-1 hour')),
        ],
        [
            'id' => 'BR004',
            'lotId' => 'LOT004',
            'wasteCategory' => 'Glass',
            'quantity' => 800,
            'unit' => 'kg',
            'currentHighestBid' => 320000.00,
            'biddingCompany' => 'GlassRecyclers Inc.',
            'status' => 'active',
            'endTime' => date('Y-m-d H:i:s', strtotime('+6 hours')),
        ],
        [
            'id' => 'BR005',
            'lotId' => 'LOT005',
            'wasteCategory' => 'Paper',
            'quantity' => 150,
            'unit' => 'kg',
            'currentHighestBid' => 600000.00,
            'biddingCompany' => 'TechRecycle Solutions',
            'status' => 'completed',
            'endTime' => date('Y-m-d H:i:s', strtotime('-2 hours')),
        ],
    ],

    // Pickup requests
    'pickup_requests' => [
        [
            'id' => 'PR001',
            'customerId' => 'C001',
            'customerName' => 'Alice Johnson',
            'address' => '123 Green St, Eco City',
            'wasteCategories' => ['Plastic', 'Paper'],
            'timeSlot' => '09:00-11:00',
            'status' => 'pending',
            'collectorId' => null,
            'collectorName' => null,
        ],
        [
            'id' => 'PR002',
            'customerId' => 'C002',
            'customerName' => 'Bob Smith',
            'address' => '456 Recycle Ave, Green Town',
            'wasteCategories' => ['Glass', 'Metal'],
            'timeSlot' => '11:00-13:00',
            'status' => 'assigned',
            'collectorId' => 'COL001',
            'collectorName' => 'Mike Wilson',
        ],
        [
            'id' => 'PR003',
            'customerId' => 'C003',
            'customerName' => 'Carol Davis',
            'address' => '789 Eco Blvd, Sustainable City',
            'wasteCategories' => ['Paper', 'Cardboard'],
            'timeSlot' => '14:00-16:00',
            'status' => 'pending',
            'collectorId' => null,
            'collectorName' => null,
        ],
        [
            'id' => 'PR004',
            'customerId' => 'C004',
            'customerName' => 'David Brown',
            'address' => '321 Sustainability Lane, Green Valley',
            'wasteCategories' => ['Plastic', 'Metal'],
            'timeSlot' => '16:00-18:00',
            'status' => 'completed',
            'collectorId' => 'COL002',
            'collectorName' => 'Sarah Brown',
        ],
    ],

    // Time slots
    'time_slots' => ['09:00-11:00', '11:00-13:00', '14:00-16:00', '16:00-18:00'],
];
?>