<?php
return [
    'defaults' => [
        'name_label' => 'Full name',
        'name_placeholder' => 'Your full name',
    ],
    'roles' => [
        'customer' => [
            'label' => 'Customer',
            'option' => 'Customer — Track recycling requests',
            'summary' => 'Ideal for residents scheduling and monitoring recycling pickups.',
            'fields' => [
                [
                    'name' => 'phone',
                    'label' => 'Phone number',
                    'type' => 'tel',
                    'placeholder' => '07XXXXXXXX',
                    'help' => 'Use a 10-digit mobile number starting with 0.',
                    'rules' => ['required', 'regex:/^0\d{9}$/'],
                    'store' => 'user',
                    'column' => 'phone',
                    'attributes' => [
                        'pattern' => '^0\\d{9}$',
                        'maxlength' => '10',
                        'inputmode' => 'numeric',
                    ],
                ],
                [
                    'name' => 'address',
                    'label' => 'Address',
                    'type' => 'textarea',
                    'placeholder' => 'Street address, city',
                    'rules' => ['required', 'max:255'],
                    'store' => 'user',
                    'column' => 'address',
                    'attributes' => [
                        'rows' => '3',
                    ],
                ],
                [
                    'name' => 'postalCode',
                    'label' => 'Postal code',
                    'type' => 'text',
                    'placeholder' => 'Postal code',
                    'help' => 'Numeric, up to 5 digits.',
                    'rules' => ['required', 'regex:/^\d{1,5}$/'],
                    'store' => 'metadata',
                    'attributes' => [
                        'pattern' => '^\d{1,5}$',
                        'maxlength' => '5',
                        'inputmode' => 'numeric',
                    ],
                ],
                [
                    'name' => 'bankAccount',
                    'label' => 'Bank account number',
                    'type' => 'text',
                    'placeholder' => 'e.g. 1234567890',
                    'rules' => ['nullable', 'min:4', 'max:32'],
                    'store' => 'metadata',
                ],
            ],
        ],
        'collector' => [
            'label' => 'Collector',
            'option' => 'Collector — Manage pickups & routes',
            'summary' => 'Optimized for field teams coordinating route assignments and pickups.',
            'fields' => [
                [
                    'name' => 'phone',
                    'label' => 'Contact number',
                    'type' => 'tel',
                    'placeholder' => '07XXXXXXXX',
                    'rules' => ['required', 'regex:/^0\d{9}$/'],
                    'help' => 'Reachable mobile number for dispatch.',
                    'store' => 'user',
                    'column' => 'phone',
                    'attributes' => [
                        'pattern' => '^0\\d{9}$',
                        'maxlength' => '10',
                        'inputmode' => 'numeric',
                    ],
                ],
                [
                    'name' => 'serviceArea',
                    'label' => 'Primary service area',
                    'type' => 'text',
                    'placeholder' => 'District / zone you operate in',
                    'rules' => ['required', 'max:120'],
                    'store' => 'metadata',
                ],
                [
                    'name' => 'vehiclePreference',
                    'label' => 'Preferred vehicle type',
                    'type' => 'select',
                    'options' => [
                        'truck' => 'Small truck',
                        'van' => 'Van',
                        'three_wheeler' => 'Three-wheeler',
                        'bike' => 'Bike',
                    ],
                    'rules' => ['required', 'in:truck,van,three_wheeler,bike'],
                    'store' => 'metadata',
                ],
                [
                    'name' => 'licenseNumber',
                    'label' => 'License number',
                    'type' => 'text',
                    'placeholder' => 'Driving license or permit',
                    'rules' => ['required', 'max:40'],
                    'store' => 'metadata',
                ],
            ],
        ],
        'company' => [
            'label' => 'Company',
            'option' => 'Company — Operations & analytics',
            'summary' => 'Built for company managers supervising recycling performance and KPIs.',
            'overrides' => [
                'name_label' => 'Account owner name',
                'name_placeholder' => 'Main contact full name',
            ],
            'fields' => [
                [
                    'name' => 'companyName',
                    'label' => 'Company name',
                    'type' => 'text',
                    'placeholder' => 'EcoCycle Industries',
                    'rules' => ['required', 'max:150'],
                    'store' => 'metadata',
                ],
                [
                    'name' => 'contactPerson',
                    'label' => 'Primary contact person',
                    'type' => 'text',
                    'placeholder' => 'Who should we reach out to?',
                    'rules' => ['required', 'max:120'],
                    'store' => 'metadata',
                ],
                [
                    'name' => 'companyPhone',
                    'label' => 'Company phone',
                    'type' => 'tel',
                    'placeholder' => '07XXXXXXXX',
                    'rules' => ['required', 'regex:/^0\d{9}$/'],
                    'store' => 'user',
                    'column' => 'phone',
                    'attributes' => [
                        'pattern' => '^0\\d{9}$',
                        'maxlength' => '10',
                        'inputmode' => 'numeric',
                    ],
                ],
                [
                    'name' => 'registrationNumber',
                    'label' => 'Business registration number',
                    'type' => 'text',
                    'placeholder' => 'BR123456',
                    'rules' => ['required', 'max:64'],
                    'store' => 'metadata',
                ],
                [
                    'name' => 'address',
                    'label' => 'Head office address',
                    'type' => 'textarea',
                    'placeholder' => 'Registered business address',
                    'rules' => ['required', 'max:255'],
                    'store' => 'user',
                    'column' => 'address',
                    'attributes' => [
                        'rows' => '3',
                    ],
                ],
            ],
        ],
        'admin' => [
            'label' => 'Admin',
            'option' => 'Admin — Platform configuration',
            'summary' => 'Reserved for administrators configuring roles, permissions, and platform settings.',
            'fields' => [
                [
                    'name' => 'invitationCode',
                    'label' => 'Invitation code',
                    'type' => 'text',
                    'placeholder' => 'Enter provided code',
                    'rules' => ['required', 'equals:ADMIN2025'],
                    'store' => 'metadata',
                    'help' => 'Only authorized administrators have this code.',
                ],
            ],
        ],
    ],
];
